# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'YouTubeApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YouTubeApp
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'youtube-ios-player-helper', '~> 0.1'
  
  target 'YouTubeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YouTubeAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
